//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace LSOmni.DataAccess.BOConnection.PreCommon.OmniWrapper2 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OmniWrapper2_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/OmniWrapper2")]
    public partial class OmniWrapper2 : MySoapHttpClientProtocol
    {
        
        private System.Threading.SendOrPostCallback GetDirectMarketingInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback MemberContactCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMemberAttributesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OmniWrapper2() {
            this.Url = global::LSOmni.DataAccess.BOConnection.PreCommon.Properties.Settings.Default.LSOmni_DataAccess_BOConnection_PreCommon_OmniWrapper2_OmniWrapper2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDirectMarketingInfoCompletedEventHandler GetDirectMarketingInfoCompleted;
        
        /// <remarks/>
        public event MemberContactCreateCompletedEventHandler MemberContactCreateCompleted;
        
        /// <remarks/>
        public event UpdateMemberAttributesCompletedEventHandler UpdateMemberAttributesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/OmniWrapper2:GetDirectMarketingInfo", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/OmniWrapper2", ResponseElementName="GetDirectMarketingInfo_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/OmniWrapper2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetDirectMarketingInfo(ref string responseCode, ref string errorText, string cardId, string itemNo, string storeNo, ref RootGetDirectMarketingInfo loadMemberDirMarkInfoXML) {
            object[] results = this.Invoke("GetDirectMarketingInfo", new object[] {
                        responseCode,
                        errorText,
                        cardId,
                        itemNo,
                        storeNo,
                        loadMemberDirMarkInfoXML});
            responseCode = ((string)(results[0]));
            errorText = ((string)(results[1]));
            loadMemberDirMarkInfoXML = ((RootGetDirectMarketingInfo)(results[2]));
        }
        
        /// <remarks/>
        public void GetDirectMarketingInfoAsync(string responseCode, string errorText, string cardId, string itemNo, string storeNo, RootGetDirectMarketingInfo loadMemberDirMarkInfoXML) {
            this.GetDirectMarketingInfoAsync(responseCode, errorText, cardId, itemNo, storeNo, loadMemberDirMarkInfoXML, null);
        }
        
        /// <remarks/>
        public void GetDirectMarketingInfoAsync(string responseCode, string errorText, string cardId, string itemNo, string storeNo, RootGetDirectMarketingInfo loadMemberDirMarkInfoXML, object userState) {
            if ((this.GetDirectMarketingInfoOperationCompleted == null)) {
                this.GetDirectMarketingInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDirectMarketingInfoOperationCompleted);
            }
            this.InvokeAsync("GetDirectMarketingInfo", new object[] {
                        responseCode,
                        errorText,
                        cardId,
                        itemNo,
                        storeNo,
                        loadMemberDirMarkInfoXML}, this.GetDirectMarketingInfoOperationCompleted, userState);
        }
        
        private void OnGetDirectMarketingInfoOperationCompleted(object arg) {
            if ((this.GetDirectMarketingInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDirectMarketingInfoCompleted(this, new GetDirectMarketingInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/OmniWrapper2:MemberContactCreate", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/OmniWrapper2", ResponseElementName="MemberContactCreate_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/OmniWrapper2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MemberContactCreate(ref string responseCode, ref string errorText, ref string clubID, ref string schemeID, ref string accountID, ref string contactID, ref string cardID, ref decimal totalRemainingPoints, ref RootMemberContactCreate memberContactCreateXML) {
            object[] results = this.Invoke("MemberContactCreate", new object[] {
                        responseCode,
                        errorText,
                        clubID,
                        schemeID,
                        accountID,
                        contactID,
                        cardID,
                        totalRemainingPoints,
                        memberContactCreateXML});
            responseCode = ((string)(results[0]));
            errorText = ((string)(results[1]));
            clubID = ((string)(results[2]));
            schemeID = ((string)(results[3]));
            accountID = ((string)(results[4]));
            contactID = ((string)(results[5]));
            cardID = ((string)(results[6]));
            totalRemainingPoints = ((decimal)(results[7]));
            memberContactCreateXML = ((RootMemberContactCreate)(results[8]));
        }
        
        /// <remarks/>
        public void MemberContactCreateAsync(string responseCode, string errorText, string clubID, string schemeID, string accountID, string contactID, string cardID, decimal totalRemainingPoints, RootMemberContactCreate memberContactCreateXML) {
            this.MemberContactCreateAsync(responseCode, errorText, clubID, schemeID, accountID, contactID, cardID, totalRemainingPoints, memberContactCreateXML, null);
        }
        
        /// <remarks/>
        public void MemberContactCreateAsync(string responseCode, string errorText, string clubID, string schemeID, string accountID, string contactID, string cardID, decimal totalRemainingPoints, RootMemberContactCreate memberContactCreateXML, object userState) {
            if ((this.MemberContactCreateOperationCompleted == null)) {
                this.MemberContactCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMemberContactCreateOperationCompleted);
            }
            this.InvokeAsync("MemberContactCreate", new object[] {
                        responseCode,
                        errorText,
                        clubID,
                        schemeID,
                        accountID,
                        contactID,
                        cardID,
                        totalRemainingPoints,
                        memberContactCreateXML}, this.MemberContactCreateOperationCompleted, userState);
        }
        
        private void OnMemberContactCreateOperationCompleted(object arg) {
            if ((this.MemberContactCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MemberContactCreateCompleted(this, new MemberContactCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/OmniWrapper2:UpdateMemberAttributes", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/OmniWrapper2", ResponseElementName="UpdateMemberAttributes_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/OmniWrapper2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMemberAttributes(ref string responseCode, ref string errorText, string cardId, ref RootSetMemberAttributes setMemberAttributesXML) {
            object[] results = this.Invoke("UpdateMemberAttributes", new object[] {
                        responseCode,
                        errorText,
                        cardId,
                        setMemberAttributesXML});
            responseCode = ((string)(results[0]));
            errorText = ((string)(results[1]));
            setMemberAttributesXML = ((RootSetMemberAttributes)(results[2]));
        }
        
        /// <remarks/>
        public void UpdateMemberAttributesAsync(string responseCode, string errorText, string cardId, RootSetMemberAttributes setMemberAttributesXML) {
            this.UpdateMemberAttributesAsync(responseCode, errorText, cardId, setMemberAttributesXML, null);
        }
        
        /// <remarks/>
        public void UpdateMemberAttributesAsync(string responseCode, string errorText, string cardId, RootSetMemberAttributes setMemberAttributesXML, object userState) {
            if ((this.UpdateMemberAttributesOperationCompleted == null)) {
                this.UpdateMemberAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMemberAttributesOperationCompleted);
            }
            this.InvokeAsync("UpdateMemberAttributes", new object[] {
                        responseCode,
                        errorText,
                        cardId,
                        setMemberAttributesXML}, this.UpdateMemberAttributesOperationCompleted, userState);
        }
        
        private void OnUpdateMemberAttributesOperationCompleted(object arg) {
            if ((this.UpdateMemberAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMemberAttributesCompleted(this, new UpdateMemberAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x55000")]
    public partial class RootGetDirectMarketingInfo {
        
        private PublishedOffer[] publishedOfferField;
        
        private PublishedOfferImages[] publishedOfferImagesField;
        
        private PublishedOfferDetailLine[] publishedOfferDetailLineField;
        
        private PublishedOfferDetailLineImages[] publishedOfferDetailLineImagesField;
        
        private MemberCouponBuffer[] memberCouponBufferField;
        
        private MemberNotification[] memberNotificationField;
        
        private MemberNotificationImages[] memberNotificationImagesField;
        
        private PublishedOfferLine[] publishedOfferLineField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PublishedOffer")]
        public PublishedOffer[] PublishedOffer {
            get {
                return this.publishedOfferField;
            }
            set {
                this.publishedOfferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PublishedOfferImages")]
        public PublishedOfferImages[] PublishedOfferImages {
            get {
                return this.publishedOfferImagesField;
            }
            set {
                this.publishedOfferImagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PublishedOfferDetailLine")]
        public PublishedOfferDetailLine[] PublishedOfferDetailLine {
            get {
                return this.publishedOfferDetailLineField;
            }
            set {
                this.publishedOfferDetailLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PublishedOfferDetailLineImages")]
        public PublishedOfferDetailLineImages[] PublishedOfferDetailLineImages {
            get {
                return this.publishedOfferDetailLineImagesField;
            }
            set {
                this.publishedOfferDetailLineImagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MemberCouponBuffer")]
        public MemberCouponBuffer[] MemberCouponBuffer {
            get {
                return this.memberCouponBufferField;
            }
            set {
                this.memberCouponBufferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MemberNotification")]
        public MemberNotification[] MemberNotification {
            get {
                return this.memberNotificationField;
            }
            set {
                this.memberNotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MemberNotificationImages")]
        public MemberNotificationImages[] MemberNotificationImages {
            get {
                return this.memberNotificationImagesField;
            }
            set {
                this.memberNotificationImagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PublishedOfferLine")]
        public PublishedOfferLine[] PublishedOfferLine {
            get {
                return this.publishedOfferLineField;
            }
            set {
                this.publishedOfferLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x55000")]
    public partial class PublishedOffer {
        
        private string noField;
        
        private string discountTypeField;
        
        private string discountNoField;
        
        private string descriptionField;
        
        private string offerCategoryField;
        
        private string primaryTextField;
        
        private string secondaryTextField;
        
        private System.DateTime endingDateField;
        
        private string encodedhtmlField;
        
        public PublishedOffer() {
            this.endingDateField = new System.DateTime(0);
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string DiscountType {
            get {
                return this.discountTypeField;
            }
            set {
                this.discountTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DiscountNo {
            get {
                return this.discountNoField;
            }
            set {
                this.discountNoField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string OfferCategory {
            get {
                return this.offerCategoryField;
            }
            set {
                this.offerCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryText {
            get {
                return this.primaryTextField;
            }
            set {
                this.primaryTextField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryText {
            get {
                return this.secondaryTextField;
            }
            set {
                this.secondaryTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01")]
        public System.DateTime EndingDate {
            get {
                return this.endingDateField;
            }
            set {
                this.endingDateField = value;
            }
        }
        
        /// <remarks/>
        public string encodedhtml {
            get {
                return this.encodedhtmlField;
            }
            set {
                this.encodedhtmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x55001")]
    public partial class MemberAttribute {
        
        private string attributeCodeField;
        
        private string attributeValueField;
        
        /// <remarks/>
        public string AttributeCode {
            get {
                return this.attributeCodeField;
            }
            set {
                this.attributeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AttributeValue {
            get {
                return this.attributeValueField;
            }
            set {
                this.attributeValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x55001")]
    public partial class RootSetMemberAttributes {
        
        private MemberAttribute[] memberAttributeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MemberAttribute")]
        public MemberAttribute[] MemberAttribute {
            get {
                return this.memberAttributeField;
            }
            set {
                this.memberAttributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x55002")]
    public partial class MemberAttributeValue {
        
        private string attributeCodeField;
        
        private string attributeValueField;
        
        /// <remarks/>
        public string AttributeCode {
            get {
                return this.attributeCodeField;
            }
            set {
                this.attributeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AttributeValue {
            get {
                return this.attributeValueField;
            }
            set {
                this.attributeValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x55002")]
    public partial class ContactCreateParameters {
        
        private string loginIDField;
        
        private string passwordField;
        
        private string emailField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        private string genderField;
        
        private string phoneField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string postCodeField;
        
        private string stateProvinceRegionField;
        
        private string countryField;
        
        private string accountIDField;
        
        private string deviceIDField;
        
        private string deviceFriendlyNameField;
        
        private string externalIDField;
        
        private string externalSystemField;
        
        private string contactIDField;
        
        private string clubIDField;
        
        private string schemeIDField;
        
        private System.DateTime dateOfBirthField;
        
        private string mobilePhoneNoField;
        
        private string houseApartmentNoField;
        
        private string territoryCodeField;
        
        private string sendReceiptbyEmailField;
        
        private string authenticatorField;
        
        private string authenticationIdField;
        
        public ContactCreateParameters() {
            this.dateOfBirthField = new System.DateTime(0);
        }
        
        /// <remarks/>
        public string LoginID {
            get {
                return this.loginIDField;
            }
            set {
                this.loginIDField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StateProvinceRegion {
            get {
                return this.stateProvinceRegionField;
            }
            set {
                this.stateProvinceRegionField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
            }
        }
        
        /// <remarks/>
        public string DeviceID {
            get {
                return this.deviceIDField;
            }
            set {
                this.deviceIDField = value;
            }
        }
        
        /// <remarks/>
        public string DeviceFriendlyName {
            get {
                return this.deviceFriendlyNameField;
            }
            set {
                this.deviceFriendlyNameField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalID {
            get {
                return this.externalIDField;
            }
            set {
                this.externalIDField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalSystem {
            get {
                return this.externalSystemField;
            }
            set {
                this.externalSystemField = value;
            }
        }
        
        /// <remarks/>
        public string ContactID {
            get {
                return this.contactIDField;
            }
            set {
                this.contactIDField = value;
            }
        }
        
        /// <remarks/>
        public string ClubID {
            get {
                return this.clubIDField;
            }
            set {
                this.clubIDField = value;
            }
        }
        
        /// <remarks/>
        public string SchemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01")]
        public System.DateTime DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhoneNo {
            get {
                return this.mobilePhoneNoField;
            }
            set {
                this.mobilePhoneNoField = value;
            }
        }
        
        /// <remarks/>
        public string HouseApartmentNo {
            get {
                return this.houseApartmentNoField;
            }
            set {
                this.houseApartmentNoField = value;
            }
        }
        
        /// <remarks/>
        public string TerritoryCode {
            get {
                return this.territoryCodeField;
            }
            set {
                this.territoryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SendReceiptbyEmail {
            get {
                return this.sendReceiptbyEmailField;
            }
            set {
                this.sendReceiptbyEmailField = value;
            }
        }
        
        /// <remarks/>
        public string Authenticator {
            get {
                return this.authenticatorField;
            }
            set {
                this.authenticatorField = value;
            }
        }
        
        /// <remarks/>
        public string AuthenticationId {
            get {
                return this.authenticationIdField;
            }
            set {
                this.authenticationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x55002")]
    public partial class RootMemberContactCreate {
        
        private ContactCreateParameters[] contactCreateParametersField;
        
        private MemberAttributeValue[] memberAttributeValueField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContactCreateParameters")]
        public ContactCreateParameters[] ContactCreateParameters {
            get {
                return this.contactCreateParametersField;
            }
            set {
                this.contactCreateParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MemberAttributeValue")]
        public MemberAttributeValue[] MemberAttributeValue {
            get {
                return this.memberAttributeValueField;
            }
            set {
                this.memberAttributeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x55000")]
    public partial class PublishedOfferLine {
        
        private string publishedOfferNoField;
        
        private string discountTypeField;
        
        private string discountNoField;
        
        private int discountLineNoField;
        
        private int discountLineTypeField;
        
        private string discountLineIdField;
        
        private string discountLineDescriptionField;
        
        private string variantTypeField;
        
        private string variantCodeField;
        
        private bool excludeField;
        
        private string unitOfMeasureField;
        
        private int tableNoField;
        
        public PublishedOfferLine() {
            this.discountLineNoField = 0;
            this.discountLineTypeField = 0;
            this.excludeField = false;
            this.tableNoField = 0;
        }
        
        /// <remarks/>
        public string PublishedOfferNo {
            get {
                return this.publishedOfferNoField;
            }
            set {
                this.publishedOfferNoField = value;
            }
        }
        
        /// <remarks/>
        public string DiscountType {
            get {
                return this.discountTypeField;
            }
            set {
                this.discountTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DiscountNo {
            get {
                return this.discountNoField;
            }
            set {
                this.discountNoField = value;
            }
        }
        
        /// <remarks/>
        public int DiscountLineNo {
            get {
                return this.discountLineNoField;
            }
            set {
                this.discountLineNoField = value;
            }
        }
        
        /// <remarks/>
        public int DiscountLineType {
            get {
                return this.discountLineTypeField;
            }
            set {
                this.discountLineTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DiscountLineId {
            get {
                return this.discountLineIdField;
            }
            set {
                this.discountLineIdField = value;
            }
        }
        
        /// <remarks/>
        public string DiscountLineDescription {
            get {
                return this.discountLineDescriptionField;
            }
            set {
                this.discountLineDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string VariantType {
            get {
                return this.variantTypeField;
            }
            set {
                this.variantTypeField = value;
            }
        }
        
        /// <remarks/>
        public string VariantCode {
            get {
                return this.variantCodeField;
            }
            set {
                this.variantCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Exclude {
            get {
                return this.excludeField;
            }
            set {
                this.excludeField = value;
            }
        }
        
        /// <remarks/>
        public string UnitOfMeasure {
            get {
                return this.unitOfMeasureField;
            }
            set {
                this.unitOfMeasureField = value;
            }
        }
        
        /// <remarks/>
        public int TableNo {
            get {
                return this.tableNoField;
            }
            set {
                this.tableNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x55000")]
    public partial class MemberNotificationImages {
        
        private string keyValueField;
        
        private int displayOrderField;
        
        private string imageIdField;
        
        public MemberNotificationImages() {
            this.displayOrderField = 0;
        }
        
        /// <remarks/>
        public string KeyValue {
            get {
                return this.keyValueField;
            }
            set {
                this.keyValueField = value;
            }
        }
        
        /// <remarks/>
        public int DisplayOrder {
            get {
                return this.displayOrderField;
            }
            set {
                this.displayOrderField = value;
            }
        }
        
        /// <remarks/>
        public string ImageId {
            get {
                return this.imageIdField;
            }
            set {
                this.imageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x55000")]
    public partial class MemberNotification {
        
        private string noField;
        
        private string contactNoField;
        
        private string primaryTextField;
        
        private string secondaryTextField;
        
        private string whenDisplayField;
        
        private System.DateTime validFromDateField;
        
        private System.DateTime validToDateField;
        
        private string memberAttributeField;
        
        private string memberAttributeValueField;
        
        private string webLinkField;
        
        private string eMailDisclaimerField;
        
        private bool personalizedEMailField;
        
        private bool sendHTMLField;
        
        public MemberNotification() {
            this.validFromDateField = new System.DateTime(0);
            this.validToDateField = new System.DateTime(0);
            this.personalizedEMailField = false;
            this.sendHTMLField = false;
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string ContactNo {
            get {
                return this.contactNoField;
            }
            set {
                this.contactNoField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryText {
            get {
                return this.primaryTextField;
            }
            set {
                this.primaryTextField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryText {
            get {
                return this.secondaryTextField;
            }
            set {
                this.secondaryTextField = value;
            }
        }
        
        /// <remarks/>
        public string WhenDisplay {
            get {
                return this.whenDisplayField;
            }
            set {
                this.whenDisplayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01")]
        public System.DateTime ValidFromDate {
            get {
                return this.validFromDateField;
            }
            set {
                this.validFromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01")]
        public System.DateTime ValidToDate {
            get {
                return this.validToDateField;
            }
            set {
                this.validToDateField = value;
            }
        }
        
        /// <remarks/>
        public string MemberAttribute {
            get {
                return this.memberAttributeField;
            }
            set {
                this.memberAttributeField = value;
            }
        }
        
        /// <remarks/>
        public string MemberAttributeValue {
            get {
                return this.memberAttributeValueField;
            }
            set {
                this.memberAttributeValueField = value;
            }
        }
        
        /// <remarks/>
        public string WebLink {
            get {
                return this.webLinkField;
            }
            set {
                this.webLinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("E-MailDisclaimer")]
        public string EMailDisclaimer {
            get {
                return this.eMailDisclaimerField;
            }
            set {
                this.eMailDisclaimerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PersonalizedE-Mail")]
        public bool PersonalizedEMail {
            get {
                return this.personalizedEMailField;
            }
            set {
                this.personalizedEMailField = value;
            }
        }
        
        /// <remarks/>
        public bool SendHTML {
            get {
                return this.sendHTMLField;
            }
            set {
                this.sendHTMLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x55000")]
    public partial class MemberCouponBuffer {
        
        private string couponCodeField;
        
        private string descriptionField;
        
        private string barcodeField;
        
        /// <remarks/>
        public string CouponCode {
            get {
                return this.couponCodeField;
            }
            set {
                this.couponCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x55000")]
    public partial class PublishedOfferDetailLineImages {
        
        private string keyValueField;
        
        private int displayOrderField;
        
        private string imageIdField;
        
        public PublishedOfferDetailLineImages() {
            this.displayOrderField = 0;
        }
        
        /// <remarks/>
        public string KeyValue {
            get {
                return this.keyValueField;
            }
            set {
                this.keyValueField = value;
            }
        }
        
        /// <remarks/>
        public int DisplayOrder {
            get {
                return this.displayOrderField;
            }
            set {
                this.displayOrderField = value;
            }
        }
        
        /// <remarks/>
        public string ImageId {
            get {
                return this.imageIdField;
            }
            set {
                this.imageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x55000")]
    public partial class PublishedOfferDetailLine {
        
        private string offerNoField;
        
        private int lineNoField;
        
        private string descriptionField;
        
        public PublishedOfferDetailLine() {
            this.lineNoField = 0;
        }
        
        /// <remarks/>
        public string OfferNo {
            get {
                return this.offerNoField;
            }
            set {
                this.offerNoField = value;
            }
        }
        
        /// <remarks/>
        public int LineNo {
            get {
                return this.lineNoField;
            }
            set {
                this.lineNoField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x55000")]
    public partial class PublishedOfferImages {
        
        private string keyValueField;
        
        private int displayOrderField;
        
        private string imageIdField;
        
        public PublishedOfferImages() {
            this.displayOrderField = 0;
        }
        
        /// <remarks/>
        public string KeyValue {
            get {
                return this.keyValueField;
            }
            set {
                this.keyValueField = value;
            }
        }
        
        /// <remarks/>
        public int DisplayOrder {
            get {
                return this.displayOrderField;
            }
            set {
                this.displayOrderField = value;
            }
        }
        
        /// <remarks/>
        public string ImageId {
            get {
                return this.imageIdField;
            }
            set {
                this.imageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetDirectMarketingInfoCompletedEventHandler(object sender, GetDirectMarketingInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDirectMarketingInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDirectMarketingInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string responseCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errorText {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public RootGetDirectMarketingInfo loadMemberDirMarkInfoXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RootGetDirectMarketingInfo)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void MemberContactCreateCompletedEventHandler(object sender, MemberContactCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MemberContactCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MemberContactCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string responseCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errorText {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string clubID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string schemeID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string accountID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string contactID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string cardID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
        
        /// <remarks/>
        public decimal totalRemainingPoints {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[7]));
            }
        }
        
        /// <remarks/>
        public RootMemberContactCreate memberContactCreateXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RootMemberContactCreate)(this.results[8]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void UpdateMemberAttributesCompletedEventHandler(object sender, UpdateMemberAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMemberAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMemberAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string responseCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errorText {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public RootSetMemberAttributes setMemberAttributesXML {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RootSetMemberAttributes)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591